version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '[%(asctime)s] [%(levelname)s] %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  "":
    handlers: [stdout]
    level: DEBUG
    propagate: True
